plugin_message:
  command:
    reload: "&a&l躲猫猫插件重载完毕"
    start:
      success: "&#FED8E2&l游戏开始运行"
      not_enough_player: "&c&l玩家数量不够，无法开始游戏"
      game_playing: "&c&l游戏正在进行中，无法开始新的游戏"
    end:
      success: "&#FED8E2&l游戏结束成功"
      game_not_exist: "&c&l不存在正在进行的游戏"
    disguise:
      game_not_start: "&c&l游戏未开始，无法进行伪装"
      only_player: "&c&l只有玩家才能使用这个命令"
      not_select_disguise: "&c&l请选择一个伪装对象"
      not_hider: "&c&l你不是躲藏者，无法变身"
  game:
    boss_bar:
      title: "&#FED8E2&l当前阶段剩余时间: &a&l%time% &#FED8E2&l秒"
    starting:
      set_disguise:
        hint: "&#FED8E2&l请点击选择你要变身的方块/实体，只能变身一次哦"
        hover: "&#FED8E2&l点击变身为%disguise%"
        msg: "&8&l>[&a&l%disguise%&8&l]<"
        seek_hint: "&#FED8E2&l本局可变身为："
      subtitle:
        hide: "&#FED8E2&l躲藏时间，请躲藏者尽快寻找躲藏位置！"
        seek: "&#FED8E2&l躲藏时间，请在倒计时结束后开始寻找"
        end: "&#FED8E2&l躲藏时间结束！开始寻找"
    playing:
      subtitle:
        hide_death: "&#FED8E2&l你已死亡，进入旁观者模式"
        all_hide_death: "&#FED8E2&l所有的躲藏者均已被找到，寻找者胜利！"
        hide_win: "&#FED8E2&l躲藏者成功躲到了游戏结束，躲藏者胜利！"
    end:
      subtitle: "&#FED8E2&l将在倒计时结束后结束游戏"
  disguise_translation:
    crafting_table: "方块:工作台"
    hay_block: "方块:干草块"
    jack_o_lantern: "方块:南瓜灯"
    smithing_table: "方块:锻造台"
    grind_stone: "方块:砂轮"
    fletching_table: "方块:制箭台"
    campfire: "方块:营火"
    bee_nest: "方块:蜂箱"
    lantern: "方块:灯笼"
    dandelion: "方块:蒲公英"
    poppy: "方块:虞美人"
    blue_orchid: "方块:兰花"
    allium: "方块:绒球葱"
    rose_bush: "方块:玫瑰丛"
    grass: "方块:草"
    amethyst_cluster: "方块:紫水晶簇"
    cake: "方块:蛋糕"
    cod: "生物:鳕鱼"
    salmon: "生物:鲑鱼"
    tropical: "生物:热带鱼"
    axolotl: "生物:美西螈"
    sheep: "生物:绵羊"
    pig: "生物:猪"
    cow: "生物:牛"
    bee: "生物:蜜蜂"
    squid: "生物:鱿鱼"
    boat: "特殊:船"
game_cycle:
  max_second:
    starting: 30
    playing: 900
    END: 10
    DEAD: -1
seek_swap_skill:
  radius:
    x: 2
    y: 2
    z: 2
  hit_damage: 2
  miss_damage: 1