name: '${name}'
version: '${version}'
main: '${main}'
api-version: 1.13
load: POSTWORLD
authors: [ YufiriaMazenta ]
depends: [ LibsDisguises ]
folia-supported: true
description: 躲猫猫!
commands:
  hideandseek:
    aliases:
      - hs
      - has
    permission: hideandseek.command